# Site settings
title: Hustle Hunt
email: renaud.beaupre@gmail.com
description: >  Hustle Hunt is a productivity app dedicated to helping side hustlers find new product ideas
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.hustlehunt.com" # the base hostname & protocol for your site
# twitter_username:
# github_username:
social:
  name: Renaud Beaupre
  links:
    - https://angel.co/renaud-beaupre
    - https://www.linkedin.com/in/renaudbeaupre
gems:
  - jekyll-seo-tag
